### ISSUE TITLE
Plugin won't start after MM update

### ISSUE THREAD

**Issue by maxheartrate** [paphko/mmm-openhabfloorplan#12]
Hi all,
I just updated Magic Mirror. After that, mmm-openhabfloorplan seems to have a problem with launching. I did a fresh install and disabled all modules. After reenabling mmm-openhabfloorplan I get the error again.

This is my log:

`> magicmirror@2.17.1 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[23.12.2021 10:51.43.329] [LOG]   Starting MagicMirror: v2.17.1
[23.12.2021 10:51.43.351] [LOG]   Loading config ...
[23.12.2021 10:51.43.378] [LOG]   Loading module helpers ...
[23.12.2021 10:51.43.383] [LOG]   No helper found for module: alert.
[23.12.2021 10:51.43.445] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.43.448] [LOG]   Module helper loaded: updatenotification
[23.12.2021 10:51.43.453] [LOG]   No helper found for module: clock.
[23.12.2021 10:51.43.950] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.43.955] [LOG]   Module helper loaded: calendar
[23.12.2021 10:51.43.966] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.43.971] [LOG]   Module helper loaded: currentweather
[23.12.2021 10:51.43.999] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.44.003] [LOG]   Module helper loaded: weatherforecast
[23.12.2021 10:51.44.012] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/mmm-openhabfloorplan/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[23.12.2021 10:51.44.014] [LOG]   Loading module helpers ...
[23.12.2021 10:51.44.017] [LOG]   No helper found for module: alert.
[23.12.2021 10:51.44.022] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.44.025] [LOG]   Module helper loaded: updatenotification
[23.12.2021 10:51.44.030] [LOG]   No helper found for module: clock.
[23.12.2021 10:51.44.034] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.44.038] [LOG]   Module helper loaded: calendar
[23.12.2021 10:51.44.041] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.44.043] [LOG]   Module helper loaded: currentweather
[23.12.2021 10:51.44.045] [LOG]   Initializing new module helper ...
[23.12.2021 10:51.44.047] [LOG]   Module helper loaded: weatherforecast
[23.12.2021 10:51.44.052] [ERROR] App threw an error during load
[23.12.2021 10:51.44.059] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/mmm-openhabfloorplan/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/mmm-openhabfloorplan/node_helper.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[23.12.2021 10:51.44.065] [ERROR] Whoops! There was an uncaught exception...
[23.12.2021 10:51.44.080] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/mmm-openhabfloorplan/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/mmm-openhabfloorplan/node_helper.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/mmm-openhabfloorplan/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[23.12.2021 10:51.44.088] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[23.12.2021 10:51.44.091] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[23.12.2021 10:51.44.704] [LOG]   Launching application.
^C/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT`

Any ideas how I can resolve the issue?

Thank you and best wishes,
Max

**Comment by maxheartrate** [comment]
I found the fix: I had to install request.
npm install request.
